name: Podcast Diário Automatizado

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar pasta pública para RSS e áudios
        run: |
          mkdir -p ./saida/public

      - name: Rodar script do podcast
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          VOICE_A: paulistano_masculino
          VOICE_B: paulistano_feminino
          MODEL_OPENAI: gpt-4o-mini
          ELEVEN_MODEL: eleven_monolingual_v1
          SAIDA_DIR: ./saida/public
          TRILHA: trilha.mp3
          PODCAST_TITLE: 'De Mala e Dog News — Espanha para Brasileiros'
          PODCAST_AUTHOR: 'De Mala e Dog'
          PODCAST_SUMMARY: 'Notícias, dicas e curiosidades da Espanha para brasileiros, em formato de bate-papo.'
          PODCAST_FEED_PATH: ./saida/public/feed.xml
          PODCAST_AUDIO_BASE_URL: 'https://raw.githubusercontent.com/demalaedog/dmd_podcast/main/saida/public/'
        run: |
          python podcast.py
